//auth types
export const LOADING_USER = "LOADING_USER";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER";
export const IMG_UPLOADED_SUCCESSFULY = "IMG_UPLOADED_SUCCESSFULY";
//Poll types
export const ADD_POLL = "ADD_POLL";
export const DELETE_POLL = "DELETE_POLL";
export const CLEAR_POLLS = "CLEAR_POLLS";
export const TOGGLE_EDIT = "TOGGLE_EDIT";
export const EDIT_POLL = "EDIT_POLL";

export const GET_ANSWERS = "GET_ANSWERS";
